sonar.projectKey=ML-PSID_credit-risk-ml
sonar.organization=ml-psid
sonar.projectName=ML-PSID

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.coverage.exclusions=**/*

sonar.exclusions=\
  .agents/**,\
  .venv/**,\
  __pycache__/**,\
  .ruff_cache/**,\
  data/notebook/**,\
  static/image-ml/**,\
  *.png,\
  *.xls
